spring:
  datasource:
    hikari:
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 2000000
      maximumPoolSize: 20
      minimumIdle: 5
      poolName: SpringBootJPAHikariCP
    platform: postgres
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
#    database: POSTGRESQL
    generate-ddl: true
    hibernate:
#      connection:
#        provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          schema_filter_provider: co.spribe.corestructure.config.CustomSchemaFilterProvider
#        default_schema: pings
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        use_sql: true
    show-sql: true
logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 8070
api-error:
  debug-enabled: true
tables-on-startup-exclude : pings
