spring:
  datasource:
      initialization-mode: always
  jpa:
    database: default
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        hbm2ddl:
          schema_filter_provider: co.spribe.corestructure.config.CustomSchemaFilterProvider
          auto: create-drop
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        show_sql: true
        use_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 8070
api-error:
  debug-enabled: true
tables-on-startup-exclude : pings
ping-datasource:
  hikari:
    connectionTimeout: 30000
    idleTimeout: 30000
    maxLifetime: 2000000
    maximumPoolSize: 20
    minimumIdle: 5
    poolName: SpringBootJPAHikariCP
  type: com.zaxxer.hikari.HikariDataSource
  platform: postgres
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
statistic-datasource:
  hikari:
    connectionTimeout: 30000
    idleTimeout: 30000
    maxLifetime: 2000000
    maximumPoolSize: 20
    minimumIdle: 5
    poolName: SpringBootJPAHikariCP
  type: com.zaxxer.hikari.HikariDataSource
  platform: postgres
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver
